name: gendiff
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  pip install poetry
                  make install
            - name: Run pytest
              run: |
                  make pytest
            - name: Test & publish code coverage
              uses: paambaati/codeclimate-action@v5.0.0
              if: github.ref_name == 'main'
              env:
                  CC_TEST_REPORTER_ID: f3d1ced8e7d14d1dc8c4e602c0bdcb10567547f8d0e376de273ea412941f7549
              with:
                  coverageCommand: make test-coverage
                  debug: true
